default:
  image: php:8.1-fpm

stages:
  - build
  - test

variables:
  GIT_CLEAN_FLAGS: none

composer:
  # The job's stage (build, test or deploy).
  stage: build
  tags:
    - php
  before_script:
    # Install composer dependencies
    - apt-get update -y
    - apt-get install wget -y
    - wget https://composer.github.io/installer.sig -O - -q | tr -d '\n' > installer.sig
    - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    - php -r "if (hash_file('SHA384', 'composer-setup.php') === file_get_contents('installer.sig')) { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
    - php composer-setup.php
    - php -r "unlink('composer-setup.php'); unlink('installer.sig');"
  # What to run on the job.
  script:
    - php composer.phar install --no-scripts
    - cp .env.example .env

phpunit:
  stage: test
  tags:
    - php
  script:
    - ./vendor/bin/phpunit --configuration ./phpunit.xml ./tests --colors=never

codestyle:
  stage: test
  tags:
    - php
  script:
    - ./vendor/bin/phpcs --standard=PSR2 --runtime-set ignore_warnings_on_exit true --extensions=php src